### ISSUE TITLE
Transaction converting to polygon stuck

### ISSUE THREAD

**Issue by dadoc1** [quorumcontrol/hippodrome#42]
Tried to swap from BTC --> ETH on polygon.

BTC went through and recognized the confirmations.

However, attempting to sign in metamask for the final conversion to eth and I get:
Swap unable to complete
Error swapping, token please try again

Using trezor wallet for this.  

Any support?

**Comment by tobowers** [comment]
Thanks for writing. Did you try again? Don’t worry no funds are lost. You’re using Trezor though metamask?

**Comment by tobowers** [comment]
Keep the url of the swap page somewhere in your notes (or even put it here)

**Comment by dadoc1** [comment]
I appreciate the quick response.  

url of swap page is:

https://hippodrome.cryptocolosseum.com/transaction/mint/BTC/0xceaff0d9299b8bbc8b56b9a5f2b5cbfb13fd8baa/21?swap=0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619

Normally when I have signed in the past in metamask it brings up the message in my Trezor T and in this case it just did it in the browser window and did not interface with the Trezor for signing.

**Comment by dadoc1** [comment]
Also it says 0 Bitcoin received on the window...which is incorrect

![Screenshot 2021-07-25 144449](https://user-images.githubusercontent.com/82081102/126914421-c38d6467-3686-481e-9d40-f506f749b717.png)

**Comment by tobowers** [comment]
> Also it says 0 Bitcoin received on the window...which is incorrect
> 
> ![Screenshot 2021-07-25 144449](https://user-images.githubusercontent.com/82081102/126914421-c38d6467-3686-481e-9d40-f506f749b717.png)

Thank you for that. That's just a decimal place problem - will fix that ASAP

**Comment by tobowers** [comment]
> I appreciate the quick response.
> 
> url of swap page is:
> 
> https://hippodrome.cryptocolosseum.com/transaction/mint/BTC/0xceaff0d9299b8bbc8b56b9a5f2b5cbfb13fd8baa/21?swap=0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619
> 
> Normally when I have signed in the past in metamask it brings up the message in my Trezor T and in this case it just did it in the browser window and did not interface with the Trezor for signing.

Is there some place we can chat in realtime? We have a #hippodrome channel here: https://discord.gg/Z6KX7VU9ZY and i'm tobowers on all the messengers.

**Comment by tobowers** [comment]
> I appreciate the quick response.
> 
> url of swap page is:
> 
> https://hippodrome.cryptocolosseum.com/transaction/mint/BTC/0xceaff0d9299b8bbc8b56b9a5f2b5cbfb13fd8baa/21?swap=0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619
> 
> Normally when I have signed in the past in metamask it brings up the message in my Trezor T and in this case it just did it in the browser window and did not interface with the Trezor for signing.

Did you just retry the swap? sometimes it's just about the price changing and the market has been volatile.

**Comment by dadoc1** [comment]
I have tried several times to sign in Metamask including different computers and browsers with no luck.

**Comment by tobowers** [comment]
> I have tried several times to sign in Metamask including different computers and browsers with no luck.

ok - I got one suggestion from gnosis  - let's see if we can't discuss in realtime somewhere.

**Comment by tobowers** [comment]
> Normally when I have signed in the past in metamask it brings up the message in my Trezor T and in this case it just did it in the browser window and did not interface with the Trezor for signing.

Oh I am just noticing this @dadoc1 - if your Trezor didn't sign and the address is your Trezor that will be a problem. Maybe there's a misconfiguration on the metamask/trezor combo? Maybe because it's polygon?

I'm also introducing a fix here that we know is needed for Ledger/Metamask, but not sure about Trezor.

**Comment by dadoc1** [comment]
It's possible.  I've signed before using the matic/polygon bridge.  looking through other forums it looks like there is a potential issue with trezor signing from metamask.   If I am unable to sign does that mean the BTC is "stuck"?

**Comment by tobowers** [comment]
I think we will figure it out :). Is the address the razor address in the
top right?.
-- 
Topper Bowers

***@***.***
github.com/tobowers
linkedin.com/in/topperbowers

**Comment by dadoc1** [comment]
Yes shows up normally in top right.  connects fine.

**Comment by tobowers** [comment]
Could we take this to somewhere more synchronous? Like our discord or telegram, signal, etc? I'll do some more research tomorrow too.
